# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustom',
            name='frontol_id',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='usercustom',
            name='frontol_password',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
