# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20171120_1559'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='usercustom',
            index=models.Index(fields=['frontol_access_key'], name='frontol_access_key_index'),
        ),
    ]
