# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20171201_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbox',
            name='session_key',
            field=models.CharField(max_length=100, null=True, verbose_name='Сессия'),
        ),
    ]
