# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 06:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orgs', '0005_auto_20171114_1446'),
        ('cards', '0008_card_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True, verbose_name='Дата/Время')),
                ('sum', models.FloatField(default=0, verbose_name='Сумма пришедшая')),
                ('bonus_reduce', models.FloatField(default=0, verbose_name='Списание бонусов')),
                ('cashbox', models.FloatField(null=True, verbose_name='Номер кассы')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.Card', verbose_name='Карта')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.Org', verbose_name='Организация')),
            ],
        ),
    ]
