# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transaction_bonus_before'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='bonus_before',
            field=models.FloatField(null=True, verbose_name='Бонусов до операции'),
        ),
    ]
