# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_auto_20171121_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('Продажа', 'sell'), ('Списание бонусов', 'bonus_reduce'), ('Пересчет скидки', 'discount_recount'), ('Начисление бонусов', 'bonus_add')], max_length=17, null=True, verbose_name='Тип'),
        ),
    ]
