# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0016_auto_20171122_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('Продажа', 'sell'), ('Начисление бонусов', 'bonus_add'), ('Списание бонусов', 'bonus_reduce'), ('Возврат', 'refund'), ('Пересчет скидки', 'discount_recount')], max_length=17, null=True, verbose_name='Тип'),
        ),
    ]
