# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0018_auto_20171201_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('Продажа', 'sell'), ('Пересчет скидки', 'discount_recount'), ('Начисление бонусов', 'bonus_add'), ('Возврат', 'refund'), ('Списание бонусов', 'bonus_reduce')], max_length=17, null=True, verbose_name='Тип'),
        ),
    ]
