# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0023_auto_20171211_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('Возврат', 'refund'), ('Списание бонусов', 'bonus_reduce'), ('Начисление бонусов', 'bonus_add'), ('Пересчет скидки', 'discount_recount'), ('Продажа', 'sell')], max_length=17, null=True, verbose_name='Тип'),
        ),
    ]
