# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-27 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0024_auto_20171219_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('Продажа', 'sell'), ('Возврат', 'refund'), ('Пересчет скидки', 'discount_recount'), ('Списание бонусов', 'bonus_reduce'), ('Начисление бонусов', 'bonus_add')], max_length=17, null=True, verbose_name='Тип'),
        ),
    ]
