# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-02 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0027_auto_20180202_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('Возврат', 'refund'), ('Начисление бонусов', 'bonus_add'), ('Списание бонусов', 'bonus_reduce'), ('Продажа', 'sell'), ('Пересчет скидки', 'discount_recount')], max_length=17, null=True, verbose_name='Тип'),
        ),
    ]
