# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-04 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0028_auto_20180202_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('Пересчет скидки', 'discount_recount'), ('Продажа', 'sell'), ('Возврат', 'refund'), ('Списание бонусов', 'bonus_reduce'), ('Начисление бонусов', 'bonus_add')], max_length=17, null=True, verbose_name='Тип'),
        ),
    ]
