# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-15 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0035_auto_20180214_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('Продажа', 'sell'), ('Списание бонусов', 'bonus_reduce'), ('Начисление бонусов', 'bonus_add'), ('Пересчет скидки', 'discount_recount'), ('Возврат', 'refund')], max_length=17, null=True, verbose_name='Тип'),
        ),
    ]
