# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-15 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0036_auto_20180215_0621'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='base_doc_date',
            field=models.DateTimeField(null=True, verbose_name='Дата/Время документа основания'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('Начисление бонусов', 'bonus_add'), ('Пересчет скидки', 'discount_recount'), ('Продажа', 'sell'), ('Списание бонусов', 'bonus_reduce'), ('Возврат', 'refund')], max_length=17, null=True, verbose_name='Тип'),
        ),
    ]
