# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-15 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0037_auto_20180215_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('Списание бонусов', 'bonus_reduce'), ('Продажа', 'sell'), ('Начисление бонусов', 'bonus_add'), ('Возврат', 'refund'), ('Пересчет скидки', 'discount_recount')], max_length=17, null=True, verbose_name='Тип'),
        ),
    ]
