# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-15 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0038_auto_20180215_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('Начисление бонусов', 'bonus_add'), ('Возврат', 'refund'), ('Продажа', 'sell'), ('Пересчет скидки', 'discount_recount'), ('Списание бонусов', 'bonus_reduce')], max_length=17, null=True, verbose_name='Тип'),
        ),
    ]
