# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-15 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0039_auto_20180215_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('Пересчет скидки', 'discount_recount'), ('Начисление бонусов', 'bonus_add'), ('Возврат', 'refund'), ('Списание бонусов', 'bonus_reduce'), ('Продажа', 'sell')], max_length=17, null=True, verbose_name='Тип'),
        ),
    ]
