# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 07:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orgs', '0003_auto_20171113_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm', models.CharField(choices=[('bonus', 'Бонусы'), ('discount', 'Накопительная скидка')], default='bonus', max_length=100)),
                ('parameters', models.CharField(default='', max_length=400)),
                ('org', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orgs.Org')),
            ],
        ),
    ]
