# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_discountplan_time_delay'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountplan',
            name='time_delay',
            field=models.IntegerField(null=True),
        ),
    ]
