# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 08:49
from __future__ import unicode_literals
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='active_from',
            field=models.DateTimeField(default=datetime.datetime.now()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='org',
            name='active_to',
            field=models.DateTimeField(default=datetime.datetime.now()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='org',
            name='discount_plan',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
    ]
