# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0002_auto_20171113_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org',
            name='active_from',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='org',
            name='active_to',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='org',
            name='discount_plan',
            field=models.CharField(default='', max_length=3),
        ),
    ]
