# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0004_remove_org_discount_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='inn',
            field=models.CharField(default='', max_length=14),
        ),
        migrations.AddField(
            model_name='org',
            name='kpp',
            field=models.CharField(default='', max_length=14),
        ),
    ]
