# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 16:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0007_auto_20171201_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashbox',
            name='user',
        ),
        migrations.RemoveField(
            model_name='org',
            name='user',
        ),
        migrations.DeleteModel(
            name='CashBox',
        ),
    ]
