# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 07:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0002_auto_20171121_1022'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Queue',
            new_name='Task',
        ),
    ]
