# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 11:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0006_auto_20171115_1013'),
        ('queues', '0004_task_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orgs.Org'),
        ),
    ]
