# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 11:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0003_auto_20171113_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='org',
            name='discount_plan',
        ),
    ]
