# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0005_auto_20171114_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org',
            name='inn',
            field=models.CharField(default='', max_length=14, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='org',
            name='kpp',
            field=models.CharField(default='', max_length=14, verbose_name='КПП'),
        ),
        migrations.AlterField(
            model_name='org',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Наименование'),
        ),
    ]
