# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='bonus_add',
            field=models.FloatField(default=0, verbose_name='Начисление бонусов'),
        ),
    ]
