# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_auto_20171115_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='cashbox',
        ),
        migrations.AddField(
            model_name='transaction',
            name='doc_close_user',
            field=models.IntegerField(null=True, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='doc_external_id',
            field=models.IntegerField(null=True, verbose_name='Внешний номер документа'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='doc_number',
            field=models.IntegerField(null=True, verbose_name='Номер документа'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='session',
            field=models.IntegerField(null=True, verbose_name='Номер смены'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='shop',
            field=models.IntegerField(null=True, verbose_name='Номер мазагина'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='workplace',
            field=models.IntegerField(null=True, verbose_name='Код рабочего места'),
        ),
    ]
