# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_auto_20171115_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('Списание', 'reduce'), ('Начисление', 'assume')], max_length=10, null=True, verbose_name='Тип'),
        ),
    ]
