# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_auto_20171120_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('Начисление', 'assume'), ('Списание', 'reduce')], max_length=10, null=True, verbose_name='Тип'),
        ),
    ]
