# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0017_auto_20171128_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('Пересчет скидки', 'discount_recount'), ('Возврат', 'refund'), ('Списание бонусов', 'bonus_reduce'), ('Продажа', 'sell'), ('Начисление бонусов', 'bonus_add')], max_length=17, null=True, verbose_name='Тип'),
        ),
    ]
