# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0022_auto_20171204_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('Продажа', 'sell'), ('Начисление бонусов', 'bonus_add'), ('Списание бонусов', 'bonus_reduce'), ('Пересчет скидки', 'discount_recount'), ('Возврат', 'refund')], max_length=17, null=True, verbose_name='Тип'),
        ),
    ]
