# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 07:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20171121_0958'),
        ('queues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='d_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.DiscountPlan'),
        ),
        migrations.AddField(
            model_name='queue',
            name='data',
            field=models.FloatField(null=True),
        ),
    ]
