# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0005_task_org'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='operation',
            field=models.CharField(choices=[('bonus', 'Начисление бонуса'), ('discount', 'Пересчет скидки')], max_length=15),
        ),
    ]
