# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 08:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('org_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.Org')),
            ],
        ),
    ]
