# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_auto_20171108_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='bonus',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='discount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='holder_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='card',
            name='accumulation',
            field=models.FloatField(default=0),
        ),
    ]
