# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 07:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_card_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='accumulation',
            field=models.FloatField(default=0, verbose_name='Накопления'),
        ),
        migrations.AlterField(
            model_name='card',
            name='bonus',
            field=models.FloatField(default=0, verbose_name='Бонусы'),
        ),
        migrations.AlterField(
            model_name='card',
            name='code',
            field=models.CharField(max_length=20, verbose_name='Код карты'),
        ),
        migrations.AlterField(
            model_name='card',
            name='deleted',
            field=models.CharField(default='n', max_length=1, verbose_name='Признак удаления (y/n)'),
        ),
        migrations.AlterField(
            model_name='card',
            name='discount',
            field=models.FloatField(default=0, verbose_name='Процентная скидка'),
        ),
        migrations.AlterField(
            model_name='card',
            name='holder_name',
            field=models.CharField(default='', max_length=100, verbose_name='ФИО владельца'),
        ),
        migrations.AlterField(
            model_name='card',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.Org', verbose_name='Организация'),
        ),
    ]
