# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-07 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0013_auto_20171227_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='holder_phone',
            field=models.CharField(default='', max_length=20, null=True, verbose_name='Телефон'),
        ),
    ]
