# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-14 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0014_auto_20180207_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonus',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='card',
            name='holder_phone',
            field=models.CharField(default='+7', max_length=20, null=True, verbose_name='Телефон'),
        ),
    ]
