# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-14 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0016_bonus_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonus',
            name='transaction_id',
            field=models.IntegerField(null=True),
        ),
    ]
