# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-15 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0017_bonus_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonus',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
