# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20171121_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountplan',
            name='time_delay',
            field=models.TimeField(null=True),
        ),
    ]
