# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-02 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20171121_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountplan',
            name='rules',
            field=models.CharField(default='', max_length=1000, verbose_name='Правила дисконтной скидки'),
        ),
        migrations.AlterField(
            model_name='discountplan',
            name='parameters',
            field=models.CharField(default='', max_length=400, verbose_name='Параметры бонусной системы'),
        ),
    ]
