# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-02 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20180202_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountplan',
            name='parameters',
            field=models.CharField(default='', max_length=400, null=True, verbose_name='Параметры бонусной системы'),
        ),
        migrations.AlterField(
            model_name='discountplan',
            name='rules',
            field=models.CharField(default='', max_length=1000, null=True, verbose_name='Правила дисконтной скидки'),
        ),
    ]
