# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 08:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='org_pk',
            new_name='org',
        ),
    ]
