# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_auto_20171108_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='accumulation',
            field=models.FloatField(default=0),
        ),
    ]
