# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_auto_20171108_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='accumulation',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
