# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_auto_20171109_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='deleted',
            field=models.CharField(default='n', max_length=1),
        ),
    ]
