# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0009_auto_20171115_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='changes_date',
            field=models.DateField(null=True, verbose_name='Дата последних изменений'),
        ),
        migrations.AddField(
            model_name='card',
            name='last_transaction_date',
            field=models.DateField(null=True, verbose_name='Дата последней транзакции'),
        ),
        migrations.AddField(
            model_name='card',
            name='reg_date',
            field=models.DateField(null=True, verbose_name='Дата регистрации'),
        ),
        migrations.AddField(
            model_name='card',
            name='type',
            field=models.CharField(choices=[('bonus', 'Бонусная'), ('discount', 'Дисконтная'), ('combo', 'Комбинированная')], default='bonus', max_length=17, verbose_name='Тип карты'),
        ),
    ]
