# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0010_auto_20171121_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='holder_phone',
            field=models.CharField(default='', max_length=20, verbose_name='Телефон'),
        ),
    ]
