# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0011_card_holder_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='fav_date',
            field=models.DateField(null=True, verbose_name='Знаменательная дата'),
        ),
        migrations.AddField(
            model_name='card',
            name='sex',
            field=models.CharField(default='m', max_length=1, verbose_name='Пол'),
        ),
    ]
