# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20171120_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustom',
            name='frontol_access_key',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
