# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20171120_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustom',
            name='active_to',
            field=models.DateField(null=True),
        ),
    ]
