# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 16:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0008_auto_20171201_1608'),
        ('users', '0007_auto_20171201_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustom',
            name='org',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='orgs.Org'),
            preserve_default=False,
        ),
    ]
