# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 16:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_usercustom_org'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя кассы')),
                ('serial_number', models.CharField(max_length=20, verbose_name='Заводской номер кассы')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес кассы')),
                ('frontol_key', models.CharField(max_length=64, null=True, verbose_name='Ключ Frontol')),
                ('online', models.BooleanField(verbose_name='Касса онлайн')),
            ],
        ),
        migrations.RenameField(
            model_name='usercustom',
            old_name='licenses_number',
            new_name='licenses_count',
        ),
        migrations.AddField(
            model_name='cashbox',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserCustom'),
        ),
        migrations.AddIndex(
            model_name='cashbox',
            index=models.Index(fields=['frontol_key'], name='frontol_index'),
        ),
    ]
