# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_cashbox_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbox',
            name='frontol_version',
            field=models.CharField(max_length=15, null=True, verbose_name='Версия Frontol'),
        ),
        migrations.AlterField(
            model_name='cashbox',
            name='online',
            field=models.BooleanField(default=False, verbose_name='Касса онлайн'),
        ),
    ]
