# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-07 00:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20180204_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashbox',
            name='org',
        ),
        migrations.AddField(
            model_name='cashbox',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.UserCustom'),
        ),
    ]
