# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-14 17:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0008_auto_20171201_1608'),
        ('users', '0013_auto_20180207_0008'),
    ]

    operations = [
        migrations.CreateModel(
            name='COUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.Org')),
            ],
        ),
        migrations.RemoveField(
            model_name='cashbox',
            name='address',
        ),
        migrations.AddField(
            model_name='cashbox',
            name='online_from',
            field=models.DateTimeField(null=True, verbose_name='Дата последнего подключения'),
        ),
        migrations.AddField(
            model_name='cashbox',
            name='co_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.COUnit'),
        ),
    ]
